// Generated by CoffeeScript 1.3.1
(function() {
  var Dtime, StateMachine;

  Dtime = {
    client_id: "",
    client_secret: "",
    "new": function() {
      if (!this.client_secret) {
        raise("No client secret");
      }
      return new StateMachine(client_id, client_secret);
    }
  };

  StateMachine = (function() {

    StateMachine.name = 'StateMachine';

    function StateMachine() {}

    StateMachine.prototype.foo = function() {
      return "bar";
    };

    return StateMachine;

  })();

}).call(this);
